# Start from the devopsdockeruh/simple-web-service:alpine image
FROM devopsdockeruh/simple-web-service:alpine

# CMD is used to define the default arguments
CMD server

# to create image (tagged 'web-server'), run in this folder:
# docker build . -t web-server

# to run container:
# docker run web-server